In [1]:
import numpy as np

In [2]:
import random
num1 = random.randint(1, 2)
num1

1

In [46]:
(-1) ** 0

1

In [56]:
(-1) ** random.randint(0, 1)

1

In [83]:
pos = ([0,1])
pos[1]

1

In [5]:
#sum of each steps is always 3, left and down are negative, right and up are positive, randomly assigned
num_hor = (-1) ** random.randint(0, 1) * random.randint(1,2)
num_ver = (-1) ** random.randint(0, 1) * (3 - np.abs(num_hor))
count = 0
#pos = ([0,0]) #initial position, row, column. so vertical-horizontal
pos = ([np.random.randint(0,8), np.random.randint(0,8)])
grid = np.zeros(shape = (8,8))
grid[pos[0], pos[1]] = 1
print(grid)
while count < 1000 and (0 in grid):
    num_hor = (-1) ** random.randint(0, 1) * random.randint(1,2) # -1
    num_ver = (-1) ** random.randint(0, 1) * (3 - np.abs(num_hor)) #+ (3-1) = 2
    new_hor = pos[1] + num_hor
    new_ver = pos[0] + num_ver
    try:
        #print('hi', new_hor, new_ver)
        if (0 <= new_hor < 8) and (0 <= new_ver < 8) and (grid[new_ver, new_hor] != 1):
            pos[1] = new_hor
            pos[0] = new_ver
            grid[pos[0], pos[1]] = 1
    except IndexError:
        pass
    #print(grid)
    count +=1
print(grid)
#next step would be running this for every possible starting spot

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
[[0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 0. 1. 1. 1. 1. 1.]]


In [47]:
grid = np.zeros(shape = (8,8))
grid
step_loc = [0,0]
print(step_loc[0] + 1, step_loc[1] + 2)
grid[step_loc[0], step_loc[1]]
step_count = 1
while 0 in grid:
    #8 conditions if statements. 
    mv_right_s = (step_loc[0] + 1 < 7) #if true they step is possible
    mv_left_s = (step_loc[0] - 1 > 0)
    mv_up_s = (step_loc[1] + 1 > 0)
    mv_down_s = (step_loc[1] + 1 < 7)
    
    mv_right_l = (step_loc[0] + 2 < 7) #if true they step is possible
    mv_left_l = (step_loc[0] - 2 > 0)
    mv_up_l = (step_loc[1] + 2 > 0)
    mv_down_l = (step_loc[1] + 2 < 7)
    
    if mv_right_s and mv_up_l:
        not_zero = (0 == grid[step_loc[0] + 1, step_loc[1] + 2]) #true if the spot hasn't been visited
        print(grid[step_loc[0] + 1, step_loc[1] + 2])
        if not_zero:
            grid[step_loc[0] + 1, step_loc[1] + 2] = step_count
            step_loc[0] += 1
            step_loc[1] += 2
            
    #print(grid)
    step_count +=1
    if step_count > 100:
        break

1 2
0.0
0.0
0.0


IndexError: index 8 is out of bounds for axis 1 with size 8

In [27]:
0 == grid[0,0]

True

In [23]:
if True and True and True:
    print('hi')

hi


In [20]:
mv_right = (step_loc[0] - 1 > 0)
print(mv_right)
step_loc[0]

False


0

In [8]:
grid[0,0]

0.0