In [6]:
import numpy as np
import itertools 


In [7]:

  
def findsubsets(s, n): 
    return list(itertools.combinations(s, n)) 

def isSubset(a, b, m, n) : 
    #a is larger array, b is subset array, m is length of a, n is length of b
    #returns 1 if not a subset, 0 if it is a subset
    # map to store the values of array a  
    mp1 = {} 
    for i in range(m): 
        if type(a[i]) == np.ndarray:
            q = a[i].flatten
            if q not in mp1:
                mp1[q] = 0
            mp1[q] += 1
        elif a[i] not in mp1: 
            mp1[a[i]] = 0
            mp1[a[i]] += 1
      
    # flag value  
    f = 0
    for i in range(n): 
          
        # if b[i] is not present in map  
        # then array b can not be a  
        # subset of array a  
        if b[i] not in mp1: 
            f = 1
            break
          
        # if if b[i] is present in map  
        # decrement by one  
        #1 is not in main array, 0 IS in main array
        else : 
            mp1[b[i]] -= 1
              
            if (mp1[b[i]] == 0): 
                mp1.pop(b[i]) 
    return f  

In [8]:
class threesum():
    def sumer(self, nums): #nums is the array passing in. Append it to solutions
        subsets = findsubsets(nums, 3) #all subsets of size 3 in original array
        solutions = [] #add to 0
        subsets_flat = []
        solutions_aslist = [] 
        for sublist in subsets: #flatten list
            for item in sublist:
                subsets_flat.append(item)


        for i in subsets: #
            sorted_subset = np.sort(i)
            #sorted_subset = i
            if np.sum(sorted_subset) == 0:
                solutions.append(list(sorted_subset))



        for i in solutions: #make items into list from ndarray
            i = list(i)
            solutions_aslist.append(i)

        non_duplicates = set()

        for sols in solutions_aslist:
            if tuple(sols) in non_duplicates:
                pass
            else:
                non_duplicates.add(tuple(sols))
        self.solutions.append(non_duplicates)
        return non_duplicates
    
    def __init__(self, name):
        self.name = name
        self.solutions = []    # creates a new empty list for each dog

In [9]:
arr = [-1, 0, 1, 2, -1, -4]

d = threesum('arr1')
print(d.sumer(arr))
p = threesum('arr2')
print(p.sumer(arr*2))
g = threesum('arr3')
print(g.sumer([x*2 for x in arr]))

{(-1, 0, 1), (-1, -1, 2)}
{(-1, 0, 1), (-1, -1, 2), (-4, 2, 2)}
{(-2, -2, 4), (-2, 0, 2)}


In [195]:
[x*2 for x in arr]

[-2, 0, 2, 4, -2, -8]

In [187]:
arr = [-1, 0, 1, 2, -1, -4]
subsets = findsubsets(arr, 3) #all subsets of size 3 in original array
solutions = [] #add to 0
subsets_flat = []
solutions_aslist = [] 
for sublist in subsets: #flatten list
    for item in sublist:
        subsets_flat.append(item)
        

for i in subsets: #
    sorted_subset = np.sort(i)
    #sorted_subset = i
    if np.sum(sorted_subset) == 0:
        solutions.append(list(sorted_subset))
        
        

for i in solutions: #make items into list from ndarray
    i = list(i)
    solutions_aslist.append(i)
    
non_duplicates = set()

for sols in solutions_aslist:
    if tuple(sols) in non_duplicates:
        pass
    else:
        non_duplicates.add(tuple(sols))
non_duplicates

{(-1, -1, 2), (-1, 0, 1)}

In [152]:
type(solutions[0])

numpy.ndarray

In [161]:
solutions_aslist

[[-1, 0, 1], [-1, -1, 2], [-1, 0, 1]]

In [178]:
#routes = [[1, 2, 4, 6, 10], [1, 3, 8, 9, 10], [1, 2, 4, 6, 10]]
routes = solutions_aslist
dups = {tuple(x) for x in routes if routes.count(x)>1}

print(dups)

{(-1, 0, 1)}


[-1, 0, 1] is a duplicate route


In [182]:
dups

{(-1, -1, 2), (-1, 0, 1)}

In [173]:
list(dups)[0]

(-1, 0, 1)

In [177]:
solutions_aslist.count(list(dups)[0])

0

In [172]:
list(dups)[0] in solutions_aslist

False

In [129]:
sorted_solutions = []
for j in solutions:
    j = np.sort(j)
    sorted_solutions.append(j)
    print(j, type(j))
sorted_solutions

[-1  0  1] <class 'numpy.ndarray'>
[-1 -1  2] <class 'numpy.ndarray'>
[-1  0  1] <class 'numpy.ndarray'>


[array([-1,  0,  1]), array([-1, -1,  2]), array([-1,  0,  1])]

In [138]:
for e in sorted_solutions:
    e = list(e)
    print(e)
    print(isSubset(sorted_solutions, e, len(sorted_solutions), len(e)))

[-1, 0, 1]
1
[-1, -1, 2]
1
[-1, 0, 1]
1


In [111]:
solutions[0].flatten()

array([-1,  0,  1])

In [102]:
for i in solutions:
    print(i)

[-1  0  1]


In [116]:
type(solutions[0]) == np.ndarray

True

In [120]:
import itertools 
  
def findsubsets(s, n): 
    return list(itertools.combinations(s, n)) 

def isSubset(a, b, m, n) : 
    #a is larger array, b is subset array, m is length of a, n is length of b
    #returns 1 if not a subset, 0 if it is a subset
    # map to store the values of array a  
    mp1 = {} 
    for i in range(m): 
        if type(a[i]) == np.ndarray:
            q = a[i].flatten
            if q not in mp1:
                mp1[q] = 0
            mp1[q] += 1
        elif a[i] not in mp1: 
            mp1[a[i]] = 0
            mp1[a[i]] += 1
      
    # flag value  
    f = 0
    for i in range(n): 
          
        # if b[i] is not present in map  
        # then array b can not be a  
        # subset of array a  
        if b[i] not in mp1: 
            f = 1
            break
          
        # if if b[i] is present in map  
        # decrement by one  
        #1 is not in main array, 0 IS in main array
        else : 
            mp1[b[i]] -= 1
              
            if (mp1[b[i]] == 0): 
                mp1.pop(b[i]) 
    return f  
      

In [118]:
# Driver code  
arr1 = subsets_flat
arr2 = np.sort(list(subset[0]))
  
m = len(arr1)  
n = len(arr2) 
  
if (not isSubset(arr1, arr2, m, n)): 
    print("arr2[] is subset of arr1[] ") 
else: 
    print("arr2[] is not a subset of arr1[]") 

arr2[] is subset of arr1[] 


In [71]:
print(type(arr1))

<class 'list'>


In [67]:
subset

[(-1, 0, 1),
 (-1, 0, 2),
 (-1, 0, -1),
 (-1, 0, -4),
 (-1, 1, 2),
 (-1, 1, -1),
 (-1, 1, -4),
 (-1, 2, -1),
 (-1, 2, -4),
 (-1, -1, -4),
 (0, 1, 2),
 (0, 1, -1),
 (0, 1, -4),
 (0, 2, -1),
 (0, 2, -4),
 (0, -1, -4),
 (1, 2, -1),
 (1, 2, -4),
 (1, -1, -4),
 (2, -1, -4)]

In [65]:
type(list(subset[0]))

list

In [59]:
subset = findsubsets(arr, 3)
isSubset(subset, subset[0], len(subset), len(subset[0]))

1

In [ ]:
su

In [ ]:
testing = {}
for i in findsubsets(arr, 3):
    testing.append

In [50]:
findsubsets(arr, 3)

[(-1, 0, 1),
 (-1, 0, 2),
 (-1, 0, -1),
 (-1, 0, -4),
 (-1, 1, 2),
 (-1, 1, -1),
 (-1, 1, -4),
 (-1, 2, -1),
 (-1, 2, -4),
 (-1, -1, -4),
 (0, 1, 2),
 (0, 1, -1),
 (0, 1, -4),
 (0, 2, -1),
 (0, 2, -4),
 (0, -1, -4),
 (1, 2, -1),
 (1, 2, -4),
 (1, -1, -4),
 (2, -1, -4)]

In [6]:

temp_sum = 0
start_count = []
sol_set = []
num_holder = []
for i in range(len(arr)):
    temp_sum += arr[i]
    start_count.append(i)
    num_holder.append(arr[i])
    if temp_sum == 0:
        temp_sum = 0
        sol_set.append(num_holder)
        num_holder = []
        start_count = []
    #if len(start_count)

In [ ]:
#make a copy of the array that will have deleted elements
#start at i: then run through the list until 

In [7]:
sol_set

[[-1, 0, 1]]