In [ ]:
#Pascal's triangle
import numpy as np

In [ ]:
nrow = 8
row_i = [1]
all_rows = []
for i in range(0, nrow):
  prev_row = row_i
  row_i = np.zeros(i+1)
  row_i[0] = 1
  row_i[-1] = 1
  if i >= 2:
    for j in range(1, i):
      row_i[j] = np.sum(prev_row[j-1: j+1])
  print(row_i)
  all_rows.append(list(row_i))
all_rows

[1.]
[1. 1.]
[1. 2. 1.]
[1. 3. 3. 1.]
[1. 4. 6. 4. 1.]
[ 1.  5. 10. 10.  5.  1.]
[ 1.  6. 15. 20. 15.  6.  1.]
[ 1.  7. 21. 35. 35. 21.  7.  1.]


[[1.0],
 [1.0, 1.0],
 [1.0, 2.0, 1.0],
 [1.0, 3.0, 3.0, 1.0],
 [1.0, 4.0, 6.0, 4.0, 1.0],
 [1.0, 5.0, 10.0, 10.0, 5.0, 1.0],
 [1.0, 6.0, 15.0, 20.0, 15.0, 6.0, 1.0],
 [1.0, 7.0, 21.0, 35.0, 35.0, 21.0, 7.0, 1.0]]

In [ ]:
for i, x in enumerate(all_rows):
  for y,j in enumerate(x):
    x[y] = int(j)
  all_rows[i] = x
all_rows

[[1],
 [1, 1],
 [1, 2, 1],
 [1, 3, 3, 1],
 [1, 4, 6, 4, 1],
 [1, 5, 10, 10, 5, 1],
 [1, 6, 15, 20, 15, 6, 1],
 [1, 7, 21, 35, 35, 21, 7, 1]]