In [0]:
import numpy as np

In [9]:
X = np.array([ [0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1] ])

y = np.array([[0,1,1,0]]).T
print("predict:\n", y)
print("based on:\n", X)


predict:
 [[0]
 [1]
 [1]
 [0]]
based on:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [0]:
syn0 = 2 * np.random.randn(3,1) - 1 #centered at 0

In [0]:
def sigmoid(x):
  return 1. / (1 + np.exp(-x))

In [0]:
def dsigmoid(x):
  return x * (1-x)

In [0]:
def loss(prediction):
  return y - prediction

In [0]:
training = 60
np.random.seed(1)

In [11]:
l0 = X
np.dot(l0, syn0) #first layer

array([[ 0.29874596],
       [-1.38576191],
       [ 0.44349242],
       [-1.24101546]])